export type RouteAuthClass = "public" | "bearer";

export type RouteInventoryItem = {
  method: "GET" | "POST" | "PUT" | "DELETE";
  path: string;
  auth: RouteAuthClass;
  mvp: boolean;
};

export const routeInventory: RouteInventoryItem[] = [
  { method: "GET", path: "/health/live", auth: "public", mvp: true },
  { method: "GET", path: "/health/ready", auth: "public", mvp: true },
  { method: "POST", path: "/validation-demo", auth: "public", mvp: true },
  { method: "POST", path: "/api/v1/auth/register", auth: "public", mvp: true },
  { method: "POST", path: "/api/v1/auth/login", auth: "public", mvp: true },
  { method: "POST", path: "/api/v1/auth/logout", auth: "public", mvp: true },
  { method: "GET", path: "/api/v1/auth/me", auth: "bearer", mvp: true },
  { method: "POST", path: "/api/v1/auth/onboarding", auth: "bearer", mvp: true },
  { method: "GET", path: "/api/v1/users/me", auth: "bearer", mvp: true },
  { method: "PUT", path: "/api/v1/users/settings", auth: "bearer", mvp: true },
  { method: "POST", path: "/api/v1/psychologists/register", auth: "bearer", mvp: true },
  { method: "GET", path: "/api/v1/psychologists/me", auth: "bearer", mvp: true },
  { method: "PUT", path: "/api/v1/psychologists/me", auth: "bearer", mvp: true },
  { method: "POST", path: "/api/v1/psychologists/me/credential-file", auth: "bearer", mvp: true },
  { method: "POST", path: "/api/v1/psychologists/me/submit-for-review", auth: "bearer", mvp: true },
  { method: "GET", path: "/api/v1/psychologists/me/credential-file/:fileId/review-url", auth: "bearer", mvp: true },
  { method: "POST", path: "/api/v1/psychologists/me/bundles", auth: "bearer", mvp: true },
  { method: "PUT", path: "/api/v1/psychologists/me/bundles/:bundleId", auth: "bearer", mvp: true },
  { method: "DELETE", path: "/api/v1/psychologists/me/bundles/:bundleId", auth: "bearer", mvp: true },
  { method: "GET", path: "/api/v1/psychologists", auth: "public", mvp: true },
  { method: "GET", path: "/api/v1/psychologists/:psychologistId", auth: "public", mvp: true },
  { method: "GET", path: "/api/v1/psychologists/:psychologistId/sessions", auth: "public", mvp: true },
  { method: "POST", path: "/api/v1/bookings", auth: "bearer", mvp: true },
  { method: "GET", path: "/api/v1/bookings", auth: "bearer", mvp: true },
  { method: "GET", path: "/api/v1/bookings/:bookingId", auth: "bearer", mvp: true },
  { method: "POST", path: "/api/v1/bookings/:bookingId/confirm", auth: "bearer", mvp: true },
  { method: "POST", path: "/api/v1/bookings/:bookingId/reschedule", auth: "bearer", mvp: true },
  { method: "POST", path: "/api/v1/payments/pakasir/webhook", auth: "public", mvp: true },
  { method: "POST", path: "/api/v1/routine/checkin", auth: "bearer", mvp: true },
  { method: "POST", path: "/api/v1/routine/relapses", auth: "bearer", mvp: true },
  { method: "GET", path: "/api/v1/routine/statistics", auth: "bearer", mvp: true },
  { method: "GET", path: "/api/v1/routine/statistics/activity-summary", auth: "bearer", mvp: true },
  { method: "GET", path: "/api/v1/routine/relapses", auth: "bearer", mvp: true },
  { method: "GET", path: "/api/v1/routine/relapses/statistics", auth: "bearer", mvp: true },
  { method: "GET", path: "/api/v1/journals", auth: "bearer", mvp: true },
  { method: "POST", path: "/api/v1/journals", auth: "bearer", mvp: true },
  { method: "GET", path: "/api/v1/community", auth: "bearer", mvp: true },
  { method: "POST", path: "/api/v1/community", auth: "bearer", mvp: true },
  { method: "GET", path: "/api/v1/community/:postId/comments", auth: "bearer", mvp: true },
  { method: "POST", path: "/api/v1/community/:postId/comments", auth: "bearer", mvp: true },
  { method: "POST", path: "/api/v1/community/:postId/like", auth: "bearer", mvp: true },
  { method: "GET", path: "/api/v1/education", auth: "bearer", mvp: true },
  { method: "GET", path: "/api/v1/content/daily", auth: "bearer", mvp: true },
  { method: "GET", path: "/api/v1/achievements/catalog", auth: "bearer", mvp: true },
  { method: "GET", path: "/api/v1/achievements/progress", auth: "bearer", mvp: true },
  { method: "GET", path: "/api/v1/achievements/unlocked", auth: "bearer", mvp: true },
  { method: "POST", path: "/api/v1/ai/ask-coach", auth: "bearer", mvp: true },
  { method: "POST", path: "/api/v1/ai/relapse-solution", auth: "bearer", mvp: true },
  { method: "POST", path: "/api/v1/ai/relapse-prevention-plan", auth: "bearer", mvp: true },
  { method: "GET", path: "/api/v1/ai/chat-history", auth: "bearer", mvp: true },
  { method: "GET", path: "/api/v1/ai/summary", auth: "bearer", mvp: true },
  { method: "POST", path: "/api/v1/ai/onboarding-analysis", auth: "bearer", mvp: true },
  { method: "GET", path: "/api/v1/ai/persona-preferences", auth: "bearer", mvp: true },
  { method: "PUT", path: "/api/v1/ai/persona-preferences", auth: "bearer", mvp: true },
] as const;
